### ISSUE TITLE
Wildcards in Get-BuildVariables Path

### ISSUE THREAD

**Issue by Rick-2CA** [RamblingCookieMonster/BuildHelpers#18]
If I'm reading this right you have to hard code the path or the build file has to stay in the project root.  What if we add `$Path = (Resolve-Path $Path).Path` at the top of `Get-BuildVariables` to support wildcards?  As an example this would allow `Set-BuildVariables -Path $PSScriptRoot\..` when your build file is in ..\Build.

**Comment by RamblingCookieMonster** [comment]
Hi!

Makes sense to me, thanks for pointing this out!

Flipping through this now - wonder if it might be worth resolving in each spot:

* Set-BuildVariables, so that each function that calls ends up using the resolved path
* Individual functions, so that ad hoc usage supports relative / non-explicit-fullname paths

Although, I suppose if we do it in each individual function, we don't need it in Set-BuildVariables.

Feel free to submit a PR!  Otherwise, I'll probably get to it post-summit

Cheers!

**Comment by RamblingCookieMonster** [comment]
Alrighty!  Had to adjust the way we call git, but this should be working, d63b084492d6accb4b9a4b15ae8d8d9958895a26 - up on the gallery shortly, assuming I didn't break the build : )

**Comment by RamblingCookieMonster** [comment]
Closing this out - hit me up if you run into any trouble still, and thanks for the idea!
